client_id = "495e67305ac3571cd36d47c24d8bd7f1"
application_url = "https://reviews-app-shopify.vercel.app"
embedded = true
name = "Reviews"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://reviews-app-shopify.vercel.app/auth/callback",
  "https://reviews-app-shopify.vercel.app/auth/shopify/callback",
  "https://reviews-app-shopify.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = false
